//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpSource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.CodeFixResources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeFixResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeFixResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpSource.CodeFixResources", typeof(CodeFixResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use await.
        /// </summary>
        internal static string AccessingTaskResultWithoutAwaitCodeFixTitle {
            get {
                return ResourceManager.GetString("AccessingTaskResultWithoutAwaitCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Task as return type.
        /// </summary>
        internal static string AsyncMethodWithVoidReturnTypeCodeFixTitle {
            get {
                return ResourceManager.GetString("AsyncMethodWithVoidReturnTypeCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Async overload.
        /// </summary>
        internal static string AsyncOverloadsAvailableCodeFixTitle {
            get {
                return ResourceManager.GetString("AsyncOverloadsAvailableCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove condition and unreachable code..
        /// </summary>
        internal static string ConditionIsConstantCodeFixTitle {
            get {
                return ResourceManager.GetString("ConditionIsConstantCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use DateTime.UtcNow.
        /// </summary>
        internal static string DateTimeNowCodeFixTitle {
            get {
                return ResourceManager.GetString("DateTimeNowCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add [Flags] attribute.
        /// </summary>
        internal static string EnumCanHaveFlagsAttributeCodeFixTitle {
            get {
                return ResourceManager.GetString("EnumCanHaveFlagsAttributeCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implement {0}..
        /// </summary>
        internal static string EqualsAndGetHashcodeNotImplementedTogetherCodeFixTitle {
            get {
                return ResourceManager.GetString("EqualsAndGetHashcodeNotImplementedTogetherCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add accessibility modifier.
        /// </summary>
        internal static string ExplicitAccessModifiersCodeFixTitle {
            get {
                return ResourceManager.GetString("ExplicitAccessModifiersCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use powers of 2.
        /// </summary>
        internal static string FlagsEnumValuesAreNotPowersOfTwoCodeFixTitle {
            get {
                return ResourceManager.GetString("FlagsEnumValuesAreNotPowersOfTwoCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Equals() and GetHashCode().
        /// </summary>
        internal static string ImplementEqualsAndGetHashCodeCodeFixTitle {
            get {
                return ResourceManager.GetString("ImplementEqualsAndGetHashCodeCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Guid.Empty.
        /// </summary>
        internal static string NewGuidUseEmptyGuidCodeFixTitle {
            get {
                return ResourceManager.GetString("NewGuidUseEmptyGuidCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Guid.NewGuid().
        /// </summary>
        internal static string NewGuidUseNewGuidCodeFixTitle {
            get {
                return ResourceManager.GetString("NewGuidUseNewGuidCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implement as property.
        /// </summary>
        internal static string NonEncapsulatedOrMutableFieldCodeFixTitle {
            get {
                return ResourceManager.GetString("NonEncapsulatedOrMutableFieldCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use nameof().
        /// </summary>
        internal static string OnPropertyChangedWithoutNameOfOperatorCodeFixTitle {
            get {
                return ResourceManager.GetString("OnPropertyChangedWithoutNameOfOperatorCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove rethrow.
        /// </summary>
        internal static string RethrowExceptionWithoutLosingStacktraceCodeFixTitle {
            get {
                return ResourceManager.GetString("RethrowExceptionWithoutLosingStacktraceCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use expression bodied member.
        /// </summary>
        internal static string SimplifyExpressionBodiedMemberCodeFixTitle {
            get {
                return ResourceManager.GetString("SimplifyExpressionBodiedMemberCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove empty constructor.
        /// </summary>
        internal static string SingleEmptyConstructorCodeFixTitle {
            get {
                return ResourceManager.GetString("SingleEmptyConstructorCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-order placeholders.
        /// </summary>
        internal static string StringPlaceholdersInWrongOrderCodeFixTitle {
            get {
                return ResourceManager.GetString("StringPlaceholdersInWrongOrderCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implement {0}.
        /// </summary>
        internal static string StructWithoutElementaryMethodsOverriddenCodeFixTitle {
            get {
                return ResourceManager.GetString("StructWithoutElementaryMethodsOverriddenCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add cases.
        /// </summary>
        internal static string SwitchDoesNotHandleAllEnumOptionsCodeFixTitle {
            get {
                return ResourceManager.GetString("SwitchDoesNotHandleAllEnumOptionsCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add default label.
        /// </summary>
        internal static string SwitchIsMissingDefaultSectionCodeFixTitle {
            get {
                return ResourceManager.GetString("SwitchIsMissingDefaultSectionCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove -Async suffix.
        /// </summary>
        internal static string SyncMethodWithAsyncSuffixAnalyzerCodeFixTitle {
            get {
                return ResourceManager.GetString("SyncMethodWithAsyncSuffixAnalyzerCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make public.
        /// </summary>
        internal static string TestMethodWithoutPublicModifierCodeFixTitle {
            get {
                return ResourceManager.GetString("TestMethodWithoutPublicModifierCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Task.Delay.
        /// </summary>
        internal static string ThreadSleepInAsyncMethodCodeFixTitle {
            get {
                return ResourceManager.GetString("ThreadSleepInAsyncMethodCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use as.
        /// </summary>
        internal static string TryCastWithoutUsingAsNotNullCodeFixTitle {
            get {
                return ResourceManager.GetString("TryCastWithoutUsingAsNotNullCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use var.
        /// </summary>
        internal static string TypeToVarCodeFixTitle {
            get {
                return ResourceManager.GetString("TypeToVarCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use alias.
        /// </summary>
        internal static string UseAliasesInsteadOfConcreteTypeCodeFixTitle {
            get {
                return ResourceManager.GetString("UseAliasesInsteadOfConcreteTypeCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add braces.
        /// </summary>
        internal static string UsingStatementWithoutBracesCodeFixTitle {
            get {
                return ResourceManager.GetString("UsingStatementWithoutBracesCodeFixTitle", resourceCulture);
            }
        }
    }
}
