name: Build

on:
  pull_request:

concurrency:
  group: ${{ github.head_ref }}-build
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore NuGet Packages
        run: dotnet restore sharpsource.sln

      - name: Build app for release
        run: msbuild sharpsource.sln -t:rebuild -property:Configuration=Release
        env: 
          DeployExtension: False

      - name: Collect artifacts - VSIX
        uses: actions/upload-artifact@v4
        with:
          name: sharpsource.vsix
          path: SharpSource\SharpSource.Vsix\bin\Release\net472\SharpSource.vsix
          if-no-files-found: error
          retention-days: 5

      - name: Collect artifacts - nugets
        uses: actions/upload-artifact@v4
        with:
          name: sharpsource.nupkg
          path: '**/SharpSource*.nupkg'
          if-no-files-found: error
          retention-days: 5