name: Changelog Check

on:
  pull_request:

concurrency:
  group: ${{ github.head_ref }}-changelog
  cancel-in-progress: true

jobs:
  build:
    name: Verify if CHANGELOG was updated
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get version from CHANGELOG.md
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          path: ./CHANGELOG.md

      - name: Validate the version has not yet been used
        env:
          TAG: v${{ steps.changelog_reader.outputs.version }}
        run: |
          if git ls-remote --exit-code --tags origin "refs/tags/$TAG" >/dev/null 2>&1; then
            echo "::error ::tag $TAG exists already"
            exit 1
          fi